# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI Check links and Build

on:
  schedule:
    - cron: '0 8 * * *'    # (run everyday at 8AM UTC, 3AM ET)
  # Allow manual trigger of this workflow
  workflow_dispatch:
#   push:
#     branches: [ main ]

jobs:
  check-link:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      changelog: ${{ steps.python-check-link.outputs.changelog }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Cache pip
      uses: actions/cache@v2
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('./scripts/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install flake8 pytest
        pip install -r ./scripts/requirements.txt
#     - name: Lint with flake8
#       run: |
#         # stop the build if there are Python syntax errors or undefined names
#         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#     - name: Test with pytest
#       run: |
#         pytest
    - name: Run check and/or fix links
      id: python-check-link
      run: |
        # python ./scripts/main.py
        output=$(python ./scripts/main.py)
        echo "::set-output name=changelog::$output"
    - name: Print changelog
      if: ${{ steps.python-check-link.outputs.changelog != '' }}
      run: echo ${{ steps.python-check-link.outputs.changelog }}
    - name: Commit reports if exist
      run: |
        echo ${{ github.ref }}
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "ci: Automated link check $(date)" -a | exit 0
    - name: Push changes
#       if: github.ref == 'refs/heads/main'
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
    - name: Archive link check results
      uses: actions/upload-artifact@v2
      with:
        name: link-check-report
        path: ./data/link_check_report.csv

  build:
    needs: [check-link]
    if: ${{ needs.check-link.outputs.changelog != '' }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Build the site with 11ty, ref: https://www.rockyourcode.com/how-to-deploy-eleventy-to-github-pages-with-github-actions/
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        npm ci

    - name: Build
      run: |
        # Increase NODE memory
        # export NODE_OPTIONS=--max_old_space_size=4096
        npm run build
      env:
        ELEVENTY_ENV: production

    - name: Commit 'organicsyntheticfaculty.html'
      run: |
        echo ${{ github.ref }}
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git pull
        git commit -m "ci: Automated update 'organicsyntheticfaculty.html' $(date)" ./_site/'organicsyntheticfaculty.html' | exit 0

    - name: Push 'organicsyntheticfaculty.html' changes
#       if: github.ref == 'refs/heads/main'
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}